<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="7" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-09T20:12:08 EET" name="Default suite" finished-at="2021-05-09T20:12:33 EET" duration-ms="24878">
    <groups>
    </groups>
    <test started-at="2021-05-09T20:12:08 EET" name="Default test" finished-at="2021-05-09T20:12:33 EET" duration-ms="24878">
      <class name="TestLevel.NewTestForLevelTest">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:TestLevel.NewTestForLevelTest@4b5d6a01]" started-at="2021-05-09T20:12:08 EET" name="beforeClass" finished-at="2021-05-09T20:12:10 EET" duration-ms="1954" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="LeinAndbondProductScenarioTest()[pri:0, instance:TestLevel.NewTestForLevelTest@4b5d6a01]" started-at="2021-05-09T20:12:10 EET" name="LeinAndbondProductScenarioTest" finished-at="2021-05-09T20:12:32 EET" duration-ms="21973" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Free] but found [$349]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Free] but found [$349]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestLevel.NewTestForLevelTest.LeinAndbondProductScenarioTest(NewTestForLevelTest.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LeinAndbondProductScenarioTest -->
        <test-method is-config="true" signature="recordFailure(org.testng.ITestResult)[pri:0, instance:TestLevel.NewTestForLevelTest@4b5d6a01]" started-at="2021-05-09T20:12:32 EET" name="recordFailure" finished-at="2021-05-09T20:12:33 EET" duration-ms="225" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LeinAndbondProductScenarioTest status=FAILURE method=NewTestForLevelTest.LeinAndbondProductScenarioTest()[pri:0, instance:TestLevel.NewTestForLevelTest@4b5d6a01] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- recordFailure -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:TestLevel.NewTestForLevelTest@4b5d6a01]" started-at="2021-05-09T20:12:33 EET" name="afterClass" finished-at="2021-05-09T20:12:33 EET" duration-ms="689" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- TestLevel.NewTestForLevelTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
